#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  resolve_date=""
  target_command=""
  target_host=""
  target_network=""
  target_device=""
  target_gateway=""
  target_address=""
  global_setting=""
  color=""
  quiet=""
  if [[ -z "TERMUX_VERSION" ]]; then
    TERMUX_VERSION=""
  fi
}

_requirements() {
  _check_cmd \
    "activity-launch" \
    "android-activity-utils"
}

_android_blotter() {
  local \
    _command="${1}" \
    _target_host="${2}" \
    _target_device="${3}" \
    _target_network="${4}" \
    _target_gateway="${5}" \
    _target_address="${6}" \
    _global_setting="${7}" \
    _args=()
  _focused_activity="$(
    activity-focused)"
  echo \
    "${_focused_activity}"
  if [[ "${_command}" == "get" ]]; then
    _args=(
      "${_target_host}"
      "${_target_device}"
      "${_target_network}"
      "${_target_gateway}"
      )
  elif [[ "${_command}" == "set" ]]; then
    _args=(
      "${_target_host}"
      "${_target_device}"
      "${_target_address}"
      "${_global_setting}"
    )
  fi
  "_${_command}_host_address" \
    "${_args[@]}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "resolve" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "target" \
    "network" \
    "$(_get_network)"
  _set_override \
    "target" \
    "device" \
    "wlan0"
  _set_override \
    "target" \
    "gateway" \
    "n"
  _set_override \
    "global" \
    "setting" \
    "n"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Returns an host address for given network on a given network device
usage:
  ${app_name}
    [options]
    <command>
    <host>
    (<address>)
  commands:
     get                  Get address for an host
     set                  Set address for an host
  options:
     -d <device>          Specify network device
                          Default: '${target_device}'
     -n <ssid_bsid>       Specify wireless network ssid
                          Default: '${target_network}'
     -g                   Specify host is the gateway
     -G                   Global setting
                          (for set command).
                          Default: '${global_setting}'

     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  local \
    _resolve_date
  TZ=UTC \
  printf \
    -v _resolve_date \
    '%(%FT%R%z)T' \
    "${SOURCE_DATE_EPOCH}"
  _msg_info "${app_name} configuration"
  _msg_info "             Resolve date:   ${_resolve_date}"
  _msg_info "              Target host:   ${target_host}"
  _msg_info "                   Device:   ${target_device}"
  _msg_info "                  Network:   ${target_network}"
  _msg_info "                  Gateway:   ${target_gateway}"
  _msg_info "                   Global:   ${global_setting}"
}

_globals
_global_variables
_requirements
_config_user_init \
  "${app_name}"
# shellcheck disable=SC2034
while \
  getopts \
    'd:n:gGcvh?' \
    arg; do
  case \
    "${arg}" in
    d)
      override_target_device="${OPTARG}" ;;
    n)
      override_target_network="${OPTARG}" ;;
    g)
      override_target_gateway="y" ;;
    G)
      override_global_setting="y" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
    _msg_error \
      "${_msg[*]}" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
if (( $# < 2 )); then
  _msg=(
    "No command given."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _set_overrides
  _usage \
    1
fi
if (( $# < 2 )); then
  _msg=(
    "No host given."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _set_overrides
  _usage \
    1
fi
target_command="${1}"
target_host="${2}"
if (( $# == 3 )); then
  target_address="${3}"
fi
_set_overrides
_config_user_init \
  "${app_name}"
if [[ "${target_device}" == "" ]]; then
  _msg=(
    "Option '-d' is required."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _usage \
    1
fi
_show_config
app_opts=(
  "${target_command}"
  "${target_host}"
  "${target_device}"
  "${target_network}"
  "${target_gateway}"
  "${target_address}"
  "${global_setting}"
)
_android_blotter \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
